// <auto-generated />
using ARSN.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ARSN.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20180104114410_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ARSN.Models.Competition", b =>
                {
                    b.Property<string>("CompetitionID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CompetitionBegin");

                    b.Property<DateTime>("CompetitionEnd");

                    b.Property<string>("Name");

                    b.Property<string>("OrganizerID");

                    b.Property<string>("SportType");

                    b.HasKey("CompetitionID");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("ARSN.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwayResult");

                    b.Property<string>("AwayTeamID");

                    b.Property<string>("CompetitionID");

                    b.Property<string>("HomeResult");

                    b.Property<string>("HomeTeamID");

                    b.Property<string>("Type");

                    b.Property<string>("Winner");

                    b.HasKey("GameID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("ARSN.Models.Organizer", b =>
                {
                    b.Property<string>("OrganizerID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Organisation");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Surname");

                    b.HasKey("OrganizerID");

                    b.ToTable("Organizer");
                });

            modelBuilder.Entity("ARSN.Models.Team", b =>
                {
                    b.Property<string>("TeamID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Organisation");

                    b.Property<string>("TrainerName");

                    b.HasKey("TeamID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("ARSN.Models.Game", b =>
                {
                    b.HasOne("ARSN.Models.Competition")
                        .WithMany("GameList")
                        .HasForeignKey("CompetitionID");
                });
#pragma warning restore 612, 618
        }
    }
}
